### ISSUE TITLE
description missing: modifier `in_array`

### ISSUE THREAD

**Issue by iDGS** [statamic/v2-docs#158] opened 2017-01-11 17:06 UTC
YMMV, but all I see is an empty box

**Comment by iDGS** [comment] 2017-01-11 18:07
Also here: https://docs.statamic.com/modifiers/merge

**Comment by jackmcdade** [comment] 2017-01-11 18:08
Yes this is a known flexbox issue we need to fix. Thanks! No need to list all the places it affects :)

**Comment by jackmcdade** [comment] 2017-01-11 18:10
Sorry, commented on the wrong thread. Meant to be on #160

**Comment by iDGS** [comment] 2017-01-11 18:11
OK. Then, here's another: https://docs.statamic.com/modifiers/modify_date

:-)

**Comment by iDGS** [comment] 2017-01-11 18:13
(I'm noting these while actually chasing something else... stay tuned... :-)

**Comment by jackmcdade** [comment] 2017-01-11 18:13
3 issues in one, fancy!

**Comment by iDGS** [comment] 2017-03-03 02:11
(Dog was playing w/ my iPad—sorry)

**Comment by jackmcdade** [comment] 2017-06-13 15:48
Duplicate of #18

**Closed as completed by jackmcdade** 2017-06-13 15:48 UTC
